name: nutripersonal
description: Aplicativo da NutriPersonal para Android..

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.5"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^1.1.3
  cupertino_icons: ^1.0.2
  vrouter: ^1.2.1
  firebase_core: ^1.20.1
  dialog_flowtter: ^0.3.1
  firebase_auth: ^3.6.4
  form_validator: ^1.0.2
  google_sign_in: ^5.4.1
  flutter_chat_ui: ^1.6.4
  flutter_secure_storage: ^6.0.0
  cached_network_image: ^3.2.2
  uuid: ^3.0.6
  bubble: ^1.2.1
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.9.2"

# See: https://dart.dev/tools/pub/pubspec
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/img/
    - assets/icons/
    - assets/config/

  # See: https://docs.flutter.dev/cookbook/design/fonts.
  fonts:
    - family: Courgette
      fonts:
        - asset: assets/fonts/Courgette-Regular.ttf
          style: normal
          weight: 400
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          style: normal
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          style: normal
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          style: normal
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          style: normal
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          style: normal
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          style: normal
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          style: normal
          weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  image_path: "assets/icon/icon.png"
  ios: false
  android: "launcher_icon"
