name: nutripersonal
description: Aplicativo da NutriPersonal para Android..

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# See: https://dart.dev/tools/pub/pubspec
flutter:
  uses-material-design: true

  assets:
    - assets/

  # See: https://docs.flutter.dev/cookbook/design/fonts.
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Thin.ttf
          style: normal
          weight: 100
        - asset: fonts/Inter-ExtraLight.ttf
          style: normal
          weight: 200
        - asset: fonts/Inter-Light.ttf
          style: normal
          weight: 300
        - asset: fonts/Inter-Regular.ttf
          style: normal
          weight: 400
        - asset: fonts/Inter-Medium.ttf
          style: normal
          weight: 500
        - asset: fonts/Inter-SemiBold.ttf
          style: normal
          weight: 600
        - asset: fonts/Inter-Bold.ttf
          style: normal
          weight: 700
        - asset: fonts/Inter-ExtraBold.ttf
          style: normal
          weight: 800
        - asset: fonts/Inter-Black.ttf
          style: normal
          weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
